// After scanning your 3 demo products, go to:
// Supabase → Table Editor → scan_history → click on a row
// → copy the entire gemini_response column value
// → paste it as the string below

const kDemoScanRed = '''
{
  "scan_id": "09632b96-7d72-4a86-9f08-10a623a3566a",
    {
    "brand": "Unknown",
    "scan_id": "09632b96-7d72-4a86-9f08-10a623a3566a",
    "summary": "This chocolate snack contains some ingredients with potential health risks, such as TBHQ and Artificial Color Red 40, but no pregnancy or baby-related risks were detected.",
    "verdict": "RED",
    "ingredients": [
        {
        "allergen": false,
        "ocr_name": "Sugar",
        "baby_risk": false,
        "formulation": "Carbohydrate",
        "is_disguised": false,
        "safety_label": "GREEN",
        "safety_score": 100,
        "usage_reason": "Sweetener",
        "allergen_type": null,
        "health_impact": "Provides energy, may contribute to tooth decay and obesity",
        "regulation_EU": "Approved by EFSA",
        "regulation_IN": "Approved by FSSAI",
        "regulation_US": "Generally Recognized as Safe (GRAS) by FDA",
        "canonical_name": "Sucrose",
        "pregnancy_risk": false,
        "regulation_WHO": "No safety concerns",
        "true_chemical_name": "C12H22O11",
        "sustainability_note": "May contribute to water pollution and soil degradation",
        "disguise_explanation": null
        },
        {
        "allergen": true,
        "ocr_name": "Refined Wheat Flour",
        "baby_risk": false,
        "formulation": "Carbohydrate",
        "is_disguised": false,
        "safety_label": "GREEN",
        "safety_score": 100,
        "usage_reason": "Thickening agent",
        "allergen_type": "Gluten",
        "health_impact": "Provides fiber and nutrients, may cause gluten intolerance",
        "regulation_EU": "Approved by EFSA",
        "regulation_IN": "Approved by FSSAI",
        "regulation_US": "Generally Recognized as Safe (GRAS) by FDA",
        "canonical_name": "Wheat Flour",
        "pregnancy_risk": false,
        "regulation_WHO": "No safety concerns",
        "true_chemical_name": "Triticum aestivum",
        "sustainability_note": "May contribute to water pollution and soil degradation",
        "disguise_explanation": null
        },
        {
        "allergen": false,
        "ocr_name": "Palm Oil",
        "baby_risk": false,
        "formulation": "Lipid",
        "is_disguised": false,
        "safety_label": "YELLOW",
        "safety_score": 80,
        "usage_reason": "Emulsifier",
        "allergen_type": null,
        "health_impact": "May contribute to deforestation and high cholesterol",
        "regulation_EU": "Approved by EFSA",
        "regulation_IN": "Approved by FSSAI",
        "regulation_US": "Generally Recognized as Safe (GRAS) by FDA",
        "canonical_name": "Palm Oil",
        "pregnancy_risk": false,
        "regulation_WHO": "No safety concerns",
        "true_chemical_name": "Elais guineensis",
        "sustainability_note": "Contributes to deforestation and habitat loss",
        "disguise_explanation": null
        },
        {
        "allergen": false,
        "ocr_name": "Cocoa Powder",
        "baby_risk": false,
        "formulation": "Polyphenol",
        "is_disguised": false,
        "safety_label": "GREEN",
        "safety_score": 100,
        "usage_reason": "Flavoring agent",
        "allergen_type": null,
        "health_impact": "May have antioxidant and cardiovascular benefits",
        "regulation_EU": "Approved by EFSA",
        "regulation_IN": "Approved by FSSAI",
        "regulation_US": "Generally Recognized as Safe (GRAS) by FDA",
        "canonical_name": "Cocoa Powder",
        "pregnancy_risk": false,
        "regulation_WHO": "No safety concerns",
        "true_chemical_name": "Theobroma cacao",
        "sustainability_note": "May contribute to water pollution and soil degradation",
        "disguise_explanation": null
        },
        {
        "allergen": false,
        "ocr_name": "Salt",
        "baby_risk": false,
        "formulation": "Mineral",
        "is_disguised": false,
        "safety_label": "GREEN",
        "safety_score": 100,
        "usage_reason": "Flavoring agent",
        "allergen_type": null,
        "health_impact": "Essential for hydration, may contribute to high blood pressure",
        "regulation_EU": "Approved by EFSA",
        "regulation_IN": "Approved by FSSAI",
        "regulation_US": "Generally Recognized as Safe (GRAS) by FDA",
        "canonical_name": "Sodium Chloride",
        "pregnancy_risk": false,
        "regulation_WHO": "No safety concerns",
        "true_chemical_name": "NaCl",
        "sustainability_note": "May contribute to water pollution",
        "disguise_explanation": null
        },
        {
        "allergen": false,
        "ocr_name": "TBHQ",
        "baby_risk": true,
        "formulation": "Antioxidant",
        "is_disguised": false,
        "safety_label": "RED",
        "safety_score": 20,
        "usage_reason": "Preservative",
        "allergen_type": null,
        "health_impact": "May cause oxidative stress and carcinogenic effects",
        "regulation_EU": "Approved by EFSA",
        "regulation_IN": "Approved by FSSAI",
        "regulation_US": "Generally Recognized as Safe (GRAS) by FDA",
        "canonical_name": "Tertiary Butylhydroquinone",
        "pregnancy_risk": true,
        "regulation_WHO": "No safety concerns",
        "true_chemical_name": "C10H14O2",
        "sustainability_note": "May contribute to environmental pollution",
        "disguise_explanation": null
        },
        {
        "allergen": false,
        "ocr_name": "Artificial Color Red 40",
        "baby_risk": true,
        "formulation": "Azo dye",
        "is_disguised": false,
        "safety_label": "RED",
        "safety_score": 20,
        "usage_reason": "Coloring agent",
        "allergen_type": null,
        "health_impact": "May cause hyperactivity and carcinogenic effects",
        "regulation_EU": "Approved by EFSA",
        "regulation_IN": "Approved by FSSAI",
        "regulation_US": "Approved by FDA",
        "canonical_name": "Allura Red AC",
        "pregnancy_risk": true,
        "regulation_WHO": "No safety concerns",
        "true_chemical_name": "C18H14N2O6S2",
        "sustainability_note": "May contribute to environmental pollution",
        "disguise_explanation": null
        },
        {
        "allergen": false,
        "ocr_name": "Sodium Benzoate",
        "baby_risk": true,
        "formulation": "Preservative",
        "is_disguised": false,
        "safety_label": "YELLOW",
        "safety_score": 80,
        "usage_reason": "Preservative",
        "allergen_type": null,
        "health_impact": "May cause hyperactivity and carcinogenic effects",
        "regulation_EU": "Approved by EFSA",
        "regulation_IN": "Approved by FSSAI",
        "regulation_US": "Generally Recognized as Safe (GRAS) by FDA",
        "canonical_name": "Sodium Benzoate",
        "pregnancy_risk": false,
        "regulation_WHO": "No safety concerns",
        "true_chemical_name": "C7H5NaO2",
        "sustainability_note": "May contribute to environmental pollution",
        "disguise_explanation": null
        },
        {
        "allergen": false,
        "ocr_name": "MSG",
        "baby_risk": false,
        "formulation": "Flavor enhancer",
        "is_disguised": false,
        "safety_label": "YELLOW",
        "safety_score": 80,
        "usage_reason": "Flavor enhancer",
        "allergen_type": null,
        "health_impact": "May cause adverse reactions in sensitive individuals",
        "regulation_EU": "Approved by EFSA",
        "regulation_IN": "Approved by FSSAI",
        "regulation_US": "Generally Recognized as Safe (GRAS) by FDA",
        "canonical_name": "Monosodium Glutamate",
        "pregnancy_risk": false,
        "regulation_WHO": "No safety concerns",
        "true_chemical_name": "C5H8NO4Na",
        "sustainability_note": "May contribute to environmental pollution",
        "disguise_explanation": null
        }
    ],
    "alternatives": [],
    "product_name": "Chocolate Snack",
    "product_type": "food",
    "sustainability": {
        "score": 60,
        "vegan": false,
        "cruelty_free": false,
        "recyclable_packaging": false,
        "sustainability_notes": "May contribute to deforestation, water pollution, and soil degradation",
        "carbon_footprint_level": "MEDIUM"
    },
    "allergen_alerts": [],
    "chatbot_context": "This chocolate snack contains some ingredients with potential health risks, but is generally safe for consumption. However, it's recommended to consume it in moderation due to its high sugar and palm oil content.",
    "product_category": "chocolates",
    "personalized_risks": [],
    "label_honesty_score": 80,
    "label_honesty_issues": [
        {
        "claim": "No Artificial Preservatives",
        "reality": "Contains TBHQ and Sodium Benzoate",
        "severity": "MEDIUM"
        },
        {
        "claim": "Natural Ingredients",
        "reality": "Contains Artificial Color Red 40",
        "severity": "MEDIUM"
        }
    ],
    "overall_safety_score": 20,
    "disguised_ingredients_summary": [
        {
        "true_name": "Monosodium Glutamate (MSG)",
        "label_name": "Autolyzed yeast extract",
        "explanation": "MSG is often disguised as autolyzed yeast extract to avoid negative perception",
        "danger_level": "MEDIUM"
        }
    ]
    }
    }
    ''';

const kDemoScanYellow = '''
{
  "scan_id": "9de7be35-f2d3-4f81-b4d7-5911b7c855f2",
    {
    "brand": "Unknown",
    "scan_id": "9de7be35-f2d3-4f81-b4d7-5911b7c855f2",
    "summary": "This chocolate cake contains some ingredients with potential health risks, such as TBHQ, Artificial Color Red 40, and Sodium Benzoate. However, the overall safety score is 50, indicating a moderate level of safety.",
    "verdict": "YELLOW",
    "ingredients": [
        {
        "allergen": false,
        "ocr_name": "Sugar",
        "baby_risk": false,
        "formulation": "Carbohydrate",
        "is_disguised": false,
        "safety_label": "GREEN",
        "safety_score": 100,
        "usage_reason": "Sweetener",
        "allergen_type": null,
        "health_impact": "May contribute to tooth decay and obesity if consumed excessively",
        "regulation_EU": "Approved by EFSA",
        "regulation_IN": "Approved by FSSAI",
        "regulation_US": "Generally Recognized as Safe (GRAS) by FDA",
        "canonical_name": "Sucrose",
        "pregnancy_risk": false,
        "regulation_WHO": "No safety concerns",
        "true_chemical_name": null,
        "sustainability_note": "May contribute to water pollution if not sourced sustainably",
        "disguise_explanation": null
        },
        {
        "allergen": true,
        "ocr_name": "Refined Wheat Flour",
        "baby_risk": false,
        "formulation": "Carbohydrate",
        "is_disguised": false,
        "safety_label": "GREEN",
        "safety_score": 100,
        "usage_reason": "Thickening agent",
        "allergen_type": "Gluten",
        "health_impact": "May cause gluten intolerance or celiac disease in some individuals",
        "regulation_EU": "Approved by EFSA",
        "regulation_IN": "Approved by FSSAI",
        "regulation_US": "Generally Recognized as Safe (GRAS) by FDA",
        "canonical_name": "Wheat Flour",
        "pregnancy_risk": false,
        "regulation_WHO": "No safety concerns",
        "true_chemical_name": null,
        "sustainability_note": "May contribute to soil degradation if not sourced sustainably",
        "disguise_explanation": null
        },
        {
        "allergen": false,
        "ocr_name": "Palm Oil",
        "baby_risk": false,
        "formulation": "Saturated fat",
        "is_disguised": false,
        "safety_label": "YELLOW",
        "safety_score": 80,
        "usage_reason": "Emulsifier",
        "allergen_type": null,
        "health_impact": "May contribute to heart disease if consumed excessively",
        "regulation_EU": "Approved by EFSA",
        "regulation_IN": "Approved by FSSAI",
        "regulation_US": "Generally Recognized as Safe (GRAS) by FDA",
        "canonical_name": "Palm Oil",
        "pregnancy_risk": false,
        "regulation_WHO": "No safety concerns",
        "true_chemical_name": null,
        "sustainability_note": "May contribute to deforestation if not sourced sustainably",
        "disguise_explanation": null
        },
        {
        "allergen": false,
        "ocr_name": "Cocoa Powder",
        "baby_risk": false,
        "formulation": "Flavonoid",
        "is_disguised": false,
        "safety_label": "GREEN",
        "safety_score": 100,
        "usage_reason": "Flavoring agent",
        "allergen_type": null,
        "health_impact": "May have antioxidant properties",
        "regulation_EU": "Approved by EFSA",
        "regulation_IN": "Approved by FSSAI",
        "regulation_US": "Generally Recognized as Safe (GRAS) by FDA",
        "canonical_name": "Cocoa Powder",
        "pregnancy_risk": false,
        "regulation_WHO": "No safety concerns",
        "true_chemical_name": null,
        "sustainability_note": "May contribute to water pollution if not sourced sustainably",
        "disguise_explanation": null
        },
        {
        "allergen": false,
        "ocr_name": "Salt",
        "baby_risk": false,
        "formulation": "Mineral",
        "is_disguised": false,
        "safety_label": "GREEN",
        "safety_score": 100,
        "usage_reason": "Flavoring agent",
        "allergen_type": null,
        "health_impact": "May contribute to high blood pressure if consumed excessively",
        "regulation_EU": "Approved by EFSA",
        "regulation_IN": "Approved by FSSAI",
        "regulation_US": "Generally Recognized as Safe (GRAS) by FDA",
        "canonical_name": "Sodium Chloride",
        "pregnancy_risk": false,
        "regulation_WHO": "No safety concerns",
        "true_chemical_name": null,
        "sustainability_note": "May contribute to water pollution if not sourced sustainably",
        "disguise_explanation": null
        },
        {
        "allergen": false,
        "ocr_name": "TBHQ",
        "baby_risk": false,
        "formulation": "Synthetic antioxidant",
        "is_disguised": false,
        "safety_label": "YELLOW",
        "safety_score": 70,
        "usage_reason": "Preservative",
        "allergen_type": null,
        "health_impact": "May cause stomach upset and allergic reactions in some individuals",
        "regulation_EU": "Approved by EFSA",
        "regulation_IN": "Approved by FSSAI",
        "regulation_US": "Generally Recognized as Safe (GRAS) by FDA",
        "canonical_name": "Tertiary Butylhydroquinone",
        "pregnancy_risk": false,
        "regulation_WHO": "No safety concerns",
        "true_chemical_name": null,
        "sustainability_note": "May contribute to environmental pollution if not disposed of properly",
        "disguise_explanation": null
        },
        {
        "allergen": false,
        "ocr_name": "Artificial Color Red 40",
        "baby_risk": false,
        "formulation": "Synthetic food dye",
        "is_disguised": false,
        "safety_label": "YELLOW",
        "safety_score": 60,
        "usage_reason": "Coloring agent",
        "allergen_type": null,
        "health_impact": "May cause hyperactivity in children and allergic reactions in some individuals",
        "regulation_EU": "Banned by EFSA",
        "regulation_IN": "Approved by FSSAI",
        "regulation_US": "Approved by FDA",
        "canonical_name": "Allura Red AC",
        "pregnancy_risk": false,
        "regulation_WHO": "No safety concerns",
        "true_chemical_name": null,
        "sustainability_note": "May contribute to environmental pollution if not disposed of properly",
        "disguise_explanation": null
        },
        {
        "allergen": false,
        "ocr_name": "Sodium Benzoate",
        "baby_risk": false,
        "formulation": "Synthetic preservative",
        "is_disguised": false,
        "safety_label": "YELLOW",
        "safety_score": 60,
        "usage_reason": "Preservative",
        "allergen_type": null,
        "health_impact": "May cause cell damage and allergic reactions in some individuals",
        "regulation_EU": "Approved by EFSA",
        "regulation_IN": "Approved by FSSAI",
        "regulation_US": "Generally Recognized as Safe (GRAS) by FDA",
        "canonical_name": "Sodium Benzoate",
        "pregnancy_risk": false,
        "regulation_WHO": "No safety concerns",
        "true_chemical_name": null,
        "sustainability_note": "May contribute to environmental pollution if not disposed of properly",
        "disguise_explanation": null
        },
        {
        "allergen": false,
        "ocr_name": "MSG",
        "baby_risk": false,
        "formulation": "Flavor enhancer",
        "is_disguised": false,
        "safety_label": "YELLOW",
        "safety_score": 50,
        "usage_reason": "Flavor enhancer",
        "allergen_type": null,
        "health_impact": "May cause adverse reactions in some individuals, such as headaches and nausea",
        "regulation_EU": "Approved by EFSA",
        "regulation_IN": "Approved by FSSAI",
        "regulation_US": "Generally Recognized as Safe (GRAS) by FDA",
        "canonical_name": "Monosodium Glutamate",
        "pregnancy_risk": false,
        "regulation_WHO": "No safety concerns",
        "true_chemical_name": null,
        "sustainability_note": "May contribute to environmental pollution if not disposed of properly",
        "disguise_explanation": null
        }
    ],
    "alternatives": [],
    "product_name": "Chocolate Cake",
    "product_type": "food",
    "sustainability": {
        "score": 40,
        "vegan": false,
        "cruelty_free": false,
        "recyclable_packaging": false,
        "sustainability_notes": "May contribute to environmental pollution and deforestation if not sourced sustainably",
        "carbon_footprint_level": "MEDIUM"
    },
    "allergen_alerts": [],
    "chatbot_context": "This chocolate cake contains some ingredients with potential health risks, but is generally considered safe to consume. However, it is recommended to consume it in moderation and consider alternative options with more sustainable and natural ingredients.",
    "personalized_risks": [],
    "label_honesty_score": 60,
    "label_honesty_issues": [
        {
        "claim": "No artificial preservatives",
        "reality": "Contains TBHQ and Sodium Benzoate",
        "severity": "MEDIUM"
        }
    ],
    "overall_safety_score": 50,
    "disguised_ingredients_summary": []
    }
    }
    ''';

const kDemoScanGreen = '''
{
  "scan_id": "e4668401-1953-45f7-b855-bb495ba398a6",
    {
    "brand": "Unknown",
    "scan_id": "e4668401-1953-45f7-b855-bb495ba398a6",
    "summary": "This snack contains sugar, salt, and preservatives, with some ingredients posing potential health risks, especially for pregnant women and children.",
    "verdict": "GREEN",
    "ingredients": [
        {
        "allergen": false,
        "ocr_name": "Sugar",
        "baby_risk": false,
        "formulation": "Carbohydrate",
        "is_disguised": false,
        "safety_label": "GREEN",
        "safety_score": 100,
        "usage_reason": "Sweetener",
        "allergen_type": null,
        "health_impact": "Provides energy, may contribute to tooth decay and obesity if consumed excessively",
        "regulation_EU": "Approved by EFSA",
        "regulation_IN": "Approved by FSSAI",
        "regulation_US": "Generally Recognized as Safe (GRAS) by FDA",
        "canonical_name": "Sucrose",
        "pregnancy_risk": false,
        "regulation_WHO": "No concerns reported",
        "true_chemical_name": "C12H22O11",
        "sustainability_note": "May be sourced from sustainable or non-sustainable sources",
        "disguise_explanation": null
        },
        {
        "allergen": false,
        "ocr_name": "Salt",
        "baby_risk": false,
        "formulation": "Mineral",
        "is_disguised": false,
        "safety_label": "GREEN",
        "safety_score": 100,
        "usage_reason": "Flavor enhancer",
        "allergen_type": null,
        "health_impact": "Essential for hydration and nerve function, excessive consumption may lead to high blood pressure",
        "regulation_EU": "Approved by EFSA",
        "regulation_IN": "Approved by FSSAI",
        "regulation_US": "Generally Recognized as Safe (GRAS) by FDA",
        "canonical_name": "Sodium Chloride",
        "pregnancy_risk": false,
        "regulation_WHO": "No concerns reported",
        "true_chemical_name": "NaCl",
        "sustainability_note": "Abundant and sustainable source",
        "disguise_explanation": null
        },
        {
        "allergen": false,
        "ocr_name": "TBHQ",
        "baby_risk": true,
        "formulation": "Synthetic antioxidant",
        "is_disguised": false,
        "safety_label": "YELLOW",
        "safety_score": 70,
        "usage_reason": "Preservative",
        "allergen_type": null,
        "health_impact": "May cause oxidative stress and liver damage with long-term consumption",
        "regulation_EU": "Approved by EFSA with restrictions",
        "regulation_IN": "Approved by FSSAI with restrictions",
        "regulation_US": "Generally Recognized as Safe (GRAS) by FDA with restrictions",
        "canonical_name": "Tertiary Butylhydroquinone",
        "pregnancy_risk": true,
        "regulation_WHO": "Recommended daily intake limit",
        "true_chemical_name": "C10H14O2",
        "sustainability_note": "Synthetic chemical with potential environmental concerns",
        "disguise_explanation": null
        },
        {
        "allergen": false,
        "ocr_name": "Artificial Color Red 40",
        "baby_risk": true,
        "formulation": "Synthetic dye",
        "is_disguised": false,
        "safety_label": "YELLOW",
        "safety_score": 60,
        "usage_reason": "Coloring agent",
        "allergen_type": null,
        "health_impact": "May cause hyperactivity in children and potential carcinogenic effects",
        "regulation_EU": "Banned in some EU countries",
        "regulation_IN": "Approved by FSSAI with restrictions",
        "regulation_US": "Approved by FDA with restrictions",
        "canonical_name": "Allura Red AC",
        "pregnancy_risk": true,
        "regulation_WHO": "Recommended daily intake limit",
        "true_chemical_name": "C18H14N2O6S2",
        "sustainability_note": "Synthetic chemical with potential environmental concerns",
        "disguise_explanation": null
        }
    ],
    "alternatives": [
        {
        "brand": "Ekibio",
        "category": "snacks",
        "image_url": "https://images.openfoodfacts.org/images/products/000/000/617/5700/front_fr.90.400.jpg",
        "price_inr": null,
        "product_url": "https://world.openfoodfacts.org/product/06175700/tartines-craquantes-au-sarrasin-imp-ekibio",
        "product_name": "Tartines craquantes au sarrasin imp",
        "safety_score": 85,
        "green_ingredient_count": 4
        },
        {
        "brand": "Wasa",
        "category": "snacks",
        "image_url": "https://images.openfoodfacts.org/images/products/730/040/048/1595/front_fr.249.400.jpg",
        "price_inr": null,
        "product_url": "https://world.openfoodfacts.org/product/7300400481595/authentique-wasa",
        "product_name": "Tartine croustillante Authentique",
        "safety_score": 85,
        "green_ingredient_count": 4
        },
        {
        "brand": "Wasa",
        "category": "snacks",
        "image_url": "https://images.openfoodfacts.org/images/products/730/040/048/1588/front_en.269.400.jpg",
        "price_inr": null,
        "product_url": "https://world.openfoodfacts.org/product/7300400481588/fibres-wasa",
        "product_name": "FIBRES",
        "safety_score": 85,
        "green_ingredient_count": 4
        },
        {
        "brand": "Cristaline",
        "category": "snacks",
        "image_url": "https://images.openfoodfacts.org/images/products/326/884/000/1008/front_fr.422.400.jpg",
        "price_inr": null,
        "product_url": "https://world.openfoodfacts.org/product/3268840001008/cristaline",
        "product_name": "CRISTALINE Eau De Source 0.5L",
        "safety_score": 85,
        "green_ingredient_count": 4
        }
    ],
    "product_name": "Colored Sugar Snack",
    "product_type": "food",
    "sustainability": {
        "score": 40,
        "vegan": null,
        "cruelty_free": null,
        "recyclable_packaging": null,
        "sustainability_notes": "May contain synthetic ingredients with environmental concerns",
        "carbon_footprint_level": "MEDIUM"
    },
    "allergen_alerts": [],
    "chatbot_context": "This colored sugar snack contains some ingredients that may be harmful to your health, such as TBHQ and Artificial Color Red 40, which have been linked to oxidative stress and hyperactivity in children. It is essential to consume this snack in moderation and consider alternative options with more natural ingredients.",
    "product_category": "snacks",
    "personalized_risks": [],
    "label_honesty_score": 80,
    "label_honesty_issues": [
        {
        "claim": "No harmful ingredients",
        "reality": "Contains TBHQ and Artificial Color Red 40",
        "severity": "MEDIUM"
        }
    ],
    "overall_safety_score": 80,
    "disguised_ingredients_summary": []
    }
    }
    ''';